### ISSUE TITLE
Printer cảnh báo sai tiền cùng chi trả bệnh nhân ARV

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitalprinter#11]
Printer cảnh báo sai tiền cùng chi trả bệnh nhân ARV

Tiền cùng chi trả trên bảng kê là 6100 # printer cảnh báo là 69,604

![image](https://user-images.githubusercontent.com/96155021/156289022-f1eff19b-1933-4c84-a02c-3b7018058bfc.png)

bệnh nhân đối tượng 11 cấp thuốc kho 01
data lỗi
https://drive.google.com/file/d/174-T3fqJnWsxLgNOebPvCyrcgKVU6Zdj/view?usp=sharing

**Comment by o-ngtrieuhau861gmailcom** [comment]
Fix tại đây: https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/d10ab34a16953bfa6ea79a3e1aa851de02521c31
