### ISSUE TITLE
Printer - Xác nhận toa thuốc load toa của bệnh nhân nội trú

### ISSUE THREAD

**Issue by BlueTea92** [oth-dhghospital/dhg.hospitalprinter#12]
BV Sa Đéc báo lỗi chức năng xác nhân toa trên Printer load lên toa của bệnh nhân nội trú.
toa thuốc của kho đông y 04
![image](https://user-images.githubusercontent.com/97272332/156686410-ac7124fb-2b20-4803-bb84-eef48909dc3f.png)

data: https://drive.google.com/file/d/1zlSIP9rh8pJtLaLoXdEFsHtQ2NSWM_Sm/view?usp=sharing

**Comment by o-ngtrieuhau861gmailcom** [comment]
Sẽ cập nhật chức năng này lại, lấy thêm theo điều kiện chungtu.noitru = 0

**Comment by o-ngtrieuhau861gmailcom** [comment]
Fix tại đây: https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/d10ab34a16953bfa6ea79a3e1aa851de02521c31
