### ISSUE TITLE
Printer in toa nhà thuốc báo số tiền đã thay đổi

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitalprinter#13]
Printer in toa nhà thuốc báo số tiền đã thay đổi
![image](https://user-images.githubusercontent.com/96155021/159606235-60050f07-d7b5-4cbf-9bf7-b2ba9499e256.png)

data: an_bvtamthan_dt_intoakhoa13
kho thuốc: 13
ngày: 22/3/2022

**Comment by o-ngtrieuhau861gmailcom** [comment]
Trường hợp Bệnh nhân BHYT, đánh toa nhà thuốc mà trường muangoai trong bảng chứng từ lại = 0. Nếu trường hợp này trường muangoai = 1 sẽ in được, không bị lỗi lúc kiểm tra toa thay đổi

**Comment by le-an-87** [comment]
ok để em kiểm tra lại trường hợp này
