### ISSUE TITLE
Lỗi tính sai tổng tiền BHYT bệnh nhân có sử dụng thuốc Viêm gan C

### ISSUE THREAD

**Issue by nghibi** [oth-dhghospital/dhg.hospitalprinter#14]
![image](https://user-images.githubusercontent.com/91751241/160352405-90ea66b9-79d9-4011-b848-7e1e503cf17c.png)
![image](https://user-images.githubusercontent.com/91751241/160352435-7ffe90be-3f97-4d19-b938-026a7076a080.png)
![image](https://user-images.githubusercontent.com/91751241/160352464-fc725262-7c3c-4b95-9173-2a0aefd7c8d4.png)

DH server: bi_dbhospital2017026763

**Comment by o-ngtrieuhau861gmailcom** [comment]
Fix tại đây: https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/d10ab34a16953bfa6ea79a3e1aa851de02521c31
