### ISSUE TITLE
BV Đông Hải in xác nhận thuốc printer báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitalprinter#15]
BV Đông Hải in xác nhận toa thuốc bệnh án ngoại trú theo đợt Printer báo lỗi.
data: an_donghai_printer
![image](https://user-images.githubusercontent.com/96155021/160762924-9f75a163-5bf4-4d84-9252-d4ce17b26775.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Fix tại đây: https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/d10ab34a16953bfa6ea79a3e1aa851de02521c31
