### ISSUE TITLE
Hóa đơn điện tử nhà thuốc không tính được tiền thuế -BV Tim Mạch AG

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalprinter#16]
- Khi lập hóa đơn điện tử cho phiếu thu tổng của nhà thuốc chưa tính được tiền thuế giống như lập hóa đơn cho từng phiếu thu.
- Phiếu thu tổng đã lập hóa đơn điện tử nhưng trên form không hiển thị thông tin của hóa đơn điện tử(số mẫu, ký hiệu, số hóa đơn).
- Dữ liệu trên server: dbtimmach_022022, hóa đơn tổng ngày 08/02, số chứng từ của phiếu thu tổng BLT22.0001/02
Ghi chú: đã cấu hình nhà thuốc qua cổng demo.

![image](https://user-images.githubusercontent.com/99630883/160957913-ab0cbbb5-c2b4-4025-87df-c2bf03adfe92.png)
![image](https://user-images.githubusercontent.com/99630883/160957922-928fcea4-9623-428c-944f-abd6bd5b1e63.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cho anh xin dữ liệu nhé
