### ISSUE TITLE
BV Tim Mạch AG - Cảnh báo lập phiếu thu nhà thuốc khi đã được lập hóa đơn tổng.

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalprinter#17]
- Yêu cầu có **cảnh báo đã lập hóa đơn tổng** khi nhấn **Lập phiếu thu/Xóa** đối với những phiếu thu đã được lập hóa đơn tổng.(Hình 1)
- Yêu cầu có cảnh báo khi nhấn lập hóa đơn điện tử những phiếu thu <200k, hiện tại chức năng Lập hóa đơn điện tử trong form Hóa đơn điện tử và chức năng Lập hóa đơn điện tử trong danh sách BN in phiếu cũng không theo cấu hình nhỏ nhất khi gửi hóa đơn. Cũng không lấy được cấu hình Gửi hóa đơn khi Lập hoặc In phiếu thu.(Hình 2)

Hình 1
![image](https://user-images.githubusercontent.com/99630883/160970195-faa463be-701c-43ec-8fec-8a026d551577.png)

Hình 2
![image](https://user-images.githubusercontent.com/99630883/160971922-028c96d5-32eb-4710-a2a5-f848fb5aebf4.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cho anh xin dữ liệu nhé

**Comment by o-ngtrieuhau861gmailcom** [comment]
![image](https://user-images.githubusercontent.com/58720300/161187976-33f560d6-38c1-4e81-8f3b-6b986c385ee1.png)
![image](https://user-images.githubusercontent.com/58720300/161187996-f6a57b26-0fe8-4557-8df5-4e64db6e362c.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Fix tại đây: https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/d10ab34a16953bfa6ea79a3e1aa851de02521c31
