### ISSUE TITLE
Printer: tìm bệnh nhân để in bảng kê 01 không load được dữ liệu

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitalprinter#23]
Khi tìm kiếm bệnh nhân printer không load được thông tin -> không in được phiếu 01
tên data: an_dktpct_printer_inbangke_timbenhnhan
bệnh ngoại trú và bệnh án ngoại trú điều bị

tìm theo tên
![image](https://user-images.githubusercontent.com/96155021/168210751-759c8c56-9455-4c6c-a9c6-09eee57fd619.png)

tìm theo ID
![image](https://user-images.githubusercontent.com/96155021/168210782-3273d34b-ef84-4c29-8081-64c614f7d56d.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây 08e94e07bec047fc51aeefd204a3532dcc10c760

**Comment by le-an-87** [comment]
chức năng tìm bệnh ở printer ok rồi anh ơi!
