### ISSUE TITLE
Hỗ trợ chức năng xuất tên bệnh ra màn hình ti vi

### ISSUE THREAD

**Issue by o-ngtrieuhau861gmailcom** [oth-dhghospital/dhg.hospitalprinter#24]
Bệnh viện Gò Vấp thực hiện xuất tên bệnh nhân ra tivi theo phân khu, cấu hình hiện tại theo kho cấp phát, yêu cầu phát sinh cùng một kho cấp phát nhưng có nhiều khu vực xuất tivi.
Hỗ trợ: 
![image](https://user-images.githubusercontent.com/58720300/168462126-ae340e67-2f89-4f34-b734-d0b1cc197e47.png)

**Comment by nghibi** [comment]
Tuấn kiểm tra xem có ok với thực tế bệnh viện chưa? OK thì xác nhận trên này.

**Comment by anhtuandhg** [comment]
Đã ok rồi á anh !
