### ISSUE TITLE
Sử dụng HDDT ở printer - Nội Tiết

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalprinter#26]
BV Nội Tiết Quảng Ngãi sử dụng HDDT ở printer cho nhà thuốc nhưng chưa được, hiện tại có hiện menu nhưng nhấn chuột vào không được.
Data: binh_noitiet
Mabvbh: 51214
![image](https://user-images.githubusercontent.com/99630883/169926963-b6f07899-d6c2-4795-a865-516bd53da96c.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Hỗ trợ cập nhật tại 9679bbee90511f41b16197a49cf871b351d6ebe5
