### ISSUE TITLE
Printer-Bảng kê ngoại trú và BANT không gọp chung CLS nhóm 8 và nhóm 18 vào chung 1 nhóm "6. Thủ thuật-Phẫu thuật"

### ISSUE THREAD

**Issue by BlueTea92** [oth-dhghospital/dhg.hospitalprinter#27]
Bảng kê ngoại trú và BANT không gọp chung CLS nhóm 8 và nhóm 18 vào chung 1 nhóm "6. Thủ thuật-Phẫu thuật"
![ảnh](https://user-images.githubusercontent.com/97272332/169939342-c5dcc939-6890-4322-bf86-dbb2425c3f10.png)

Data: tra_medicmd_fees

    Mabn: 2022044381
    Ngày 24/05/2022 thuộc khoa: 10, phòng: 09

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây 54a16076483263e99c9b63badedec2fdd21e06fd

**Comment by BlueTea92** [comment]
ok rồi anh
