### ISSUE TITLE
Prescription_Bổ sung_Số lượng khi cấp toa cho phép gõ 2 số lẻ

### ISSUE THREAD

**Issue by minhduc2it** [oth-dhghospital/dhg.hospitalprinter#28]
BV Ung bướu Cần Thơ
![image](https://user-images.githubusercontent.com/98437757/171821835-ab535652-0e53-4ded-880d-347c0f3e7b51.png)

**Comment by nghibi** [comment]
Đức check lại dùm anh cái nha, đã mở cho CC nhập 02 số thập phân.
