### ISSUE TITLE
Printer xài HDDT

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalprinter#29]
Mở code dùm em cho 2 BV xài HDDT cho nhà thuốc ở Printer:
 92003 - VAT
 92085 - VNPT

**Comment by o-ngtrieuhau861gmailcom** [comment]
- Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/5d3fcd11494f12aa876f175aed6503699b75b7a8
