### ISSUE TITLE
Lỗi không chọn được máy in nhiệt khi in phiếu thu nhà thuốc

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalprinter#30]
Bản cũ thì sau khi in toa thuốc xong sẽ hiện form chọn máy in để in phiếu thu qua máy in nhiệt, nhưng bản mới không cho chọn, nó in luôn phiếu thu bằng máy in mặc định như toa thuốc, mặc dù đã chọn tham số khongintructieppt=1
Data: binh_nhidong, makb 2204025976, ngày 09/06

![image](https://user-images.githubusercontent.com/99630883/172813847-5929cbaf-be7e-459c-ad82-287408cca59a.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/e250ac8dc8a68150f4aa4f0b79c5194d8b6f636c
