### ISSUE TITLE
Lỗi: in bảng kê báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitalprinter#31]
Printer ngày 8/6/2020 khi in bảng kê báo lỗi
tên data: an_yhct_chandoan
![image](https://user-images.githubusercontent.com/96155021/172985420-a8f6a522-0799-4707-b873-10c77dc8202f.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/56963b8a216fb8060945c42d2965260bf516e0bc

**Comment by le-an-87** [comment]
đã fix! đã in được bảng kê rồi anh ơi.
