### ISSUE TITLE
in bảng kê hiển thị form parametter

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitalprinter#4]
khi in bảng kê lần 2 hiển thị bảng parametter.
![image](https://user-images.githubusercontent.com/96155021/146105527-fa6e56f1-de6b-4a07-a5ad-e8c3a03d66fe.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
[Đã fix rồi](https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/76354f4f39c868b302a49fad6536f052f93297a5)

**Comment by le-an-87** [comment]
đã fix
