### ISSUE TITLE
Printer báo sai số tiền bệnh nhân cần chi trả

### ISSUE THREAD

**Issue by BlueTea92** [oth-dhghospital/dhg.hospitalprinter#9]
![image](https://user-images.githubusercontent.com/97272332/155640328-fc99d671-eeb4-4b31-a826-7c16dbe58c8c.png)
![image](https://user-images.githubusercontent.com/97272332/155640376-67a1a8de-bbd2-406e-bba2-3de561f81f15.png)
- Bệnh nhân được thanh toán nguồn khác nên 1 phần nguồn khác chi trả 1 phần bệnh nhân phải đóng nhưng Printer đang thể hiện cả 2 
- Data máy chủ: tra_dbgiarai_inphieu_pri
- bệnh nhân ngày 24/02/2022
- Khoa 10, phòng 38

**Comment by o-ngtrieuhau861gmailcom** [comment]
Fix lại đây nhé: https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/d10ab34a16953bfa6ea79a3e1aa851de02521c31
